
modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="MIT"

[[mods]]

modId="scrapbags"
version="${file.jarVersion}"
displayName="Scrap Bags"

description='''

'''

[[dependencies.scrapbags]]
   modId="forge"
   mandatory=true
   versionRange="[43,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.scrapbags]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.2,1.20)"
   ordering="NONE"
   side="BOTH"
